### PR TITLE
DefaultConnection response stream reading fix

### PR DESCRIPTION
**Pull request by wsz87**
Associated with issue #14

### CODE REVIEW

**Comment by shred** [comment]
Thank you! Can you remove the `final` modifiers, to keep the code style consistent? I will merge the PR after that.

**Comment by wsz87** [comment]
It should be fine now, I've just removed finals.

**Comment by shred** [comment]
Thank you for fixing this bug! Those things always happen while one is on a vacation trip. :-) I will release a new version with the fix within the next hours.

**Comment by wsz87** [comment]
You're welcome. Moore's law is always in force :).

**Pull request merged**
