### PR TITLE
The Venify ACME server api returns 'application/json; utf-8' as the c…

### PR DESCRIPTION
**Pull request by fieldju**
…ontent header type

### CODE REVIEW

**Comment by fieldju** [comment]
I am trying this client out with Venafi's ACME implementation this is the first snag I ran into, I will make additional PRs if I run into more issues.

**Comment by fieldju** [comment]
just from looking in the file I see other places where the header might cause issues, I will install this lib in my maven local and work things out and update this PR

**Comment by fieldju** [comment]
OK, I am gonna close this PR for now and re-open a new one soon with all the fixes needed to enable Venafi's ACME impl.

So far there are a couple minor things I am noticing but I am not done yet.
Ex: 
- Venafi content-type headers have extra stuff as seen in this PR
- Venafi registration returns a 200 rather than a 201 that LetsEncrypt returns

I used your client to get the following working for LetsEncrypt
https://github.com/Nike-Inc/cerberus-lifecycle-cli/compare/highlander...feature/lets_encrypt_cert_generation?expand=1#diff-f24ea7e9d4243bc64d437eec7cd39631R220
but we also want to be able to use Venafi, so I am user testing it right now with Venafi and making fixes on my local acme4j copy and will commit everything once I have the command working again with Venafi and LetsEncrypt

**Comment by shred** [comment]
Can you give an example Content-Type header? If it's RFC conformous, I would rather prefer to use a regex instead of `contains()`, and ignore the parameter part of the header.

About the 200 and 201 return codes, they have changed a lot in the drafts and Let's Encrypt's _Boulder_ implementation, so maybe it's a good idea to just accept both, at least in the ACME v1 branch of _acme4j_.

Do you know if Venafi has plans to implement ACME v2 in the future?

**Comment by shred** [comment]
Thanks... That was obvious, I should have thought about it by myself.

Technically there is no need to send a charset along with the Content-Type header, as the ACME protocol only permits the use of utf-8 anyway. But acme4j should still accept a charset parameter if present. I regard this as a bug in acme4j that need to be fixed.

Do you want to send a PR for that? I would write a fix for that if you won't...

**Comment by fieldju** [comment]
You can go for it, since you want to do it with regexes. There are a couple
places that have that bug.

I will make a PR when I have the complete list of status code diffs
tomorrow or get you the list.

Cheers

**Pull request closed without merging**
