### PR TITLE
enable Dependabot v2

### PR DESCRIPTION
**Pull request by sullis**
https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

### CODE REVIEW

**Comment by sullis** [comment]
Ready for review @shred

**Comment by shred** [comment]
Thank you...

There is a problem with dependabot. If I invoke `mvn versions:display-dependency-updates`, it always proposes to upgrade slf4j to `2.0.0-alpha1`. It's an alpha version that is stuck there for years now, and I generally won't depend on alpha versions. With dependabot, I guess I would get an automated pull-request that would upgrade slf4j as well, which I then would have to fix manually.

Can you force dependabot to only check for `slf4j < 2` kind of updates?

**Comment by sullis** [comment]
> Can you force dependabot to only check for `slf4j < 2` kind of updates?

I have Dependabot enabled on multiple Java projects. Dependabot has never suggested upgrading to SLF4J 2.x alpha.

**Comment by shred** [comment]
OK, let's try it then. Thank you!

**Pull request merged**
